### ISSUE TITLE
Namespace wrong?

### ISSUE THREAD

**Issue by nunojusto** [utkuozdemir/argocd-helm-secret-values-example#1]
Hi @utkuozdemir, I was following your [blog](https://utkuozdemir.org/blog/argocd-helm-secrets/) about this ArgoCD shared helm values secrets and the way you used an indirection to solve the problem.
But I've found out that in your examples, your namespace may be wrong [here](https://github.com/utkuozdemir/argocd-helm-secret-values-example/blob/e609197988f08c12da7a59de4a918a2e8f05df50/apps/templates/10-postgresql.yaml#L5) and [here](https://github.com/utkuozdemir/argocd-helm-secret-values-example/blob/e609197988f08c12da7a59de4a918a2e8f05df50/apps/templates/10-grafana.yaml#L5)

Since those are ArgoCD Application manifests, they should have the namespace where argocd and not 'default' nor the 'grafana' or 'postgres' like you have also in your blog page.

But thank you for your idea. It solved (kind of) my puzzle.

**Comment by utkuozdemir** [comment]
Thanks for informing me, I fixed it on the post and on this repo.
Glad that it helped you.
Cheers.
